import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import QRCode from'qrcode';import JsBarcode from'jsbarcode';import JSZip from'jszip';
import{QrCode,Barcode,Layers3,History,Palette,Download,Copy,Sun,Moon,Upload,Printer,ScanLine,Star,Trash2,Undo2,Redo2,ImagePlus,Check,Wifi,Contact,CalendarDays,Mail,MapPin,MessageSquare,FileArchive,Command,ShieldCheck,Sparkles,X,ChevronDown,Plus,BarChart3,Code2,ArrowRight,Smartphone,Zap,WifiOff}from'lucide-react';
import'./styles.css';
const TYPES=[['qr','QR Code',QrCode],['code128','Code 128',Barcode],['upc','UPC-A',Barcode],['ean13','EAN-13',Barcode]];
const PRESETS=[['Obsidian','#101114','#ffffff'],['Ocean','#075985','#f0f9ff'],['Forest','#14532d','#f0fdf4'],['Violet','#5b21b6','#faf5ff'],['Coral','#be123c','#fff1f2']];
const TEMPLATES=[{id:'url',name:'Website',icon:QrCode,fields:['URL'],build:v=>v.URL},{id:'wifi',name:'Wi-Fi',icon:Wifi,fields:['Network','Password','Security'],build:v=>`WIFI:T:${v.Security||'WPA'};S:${v.Network||''};P:${v.Password||''};;`},{id:'contact',name:'Contact',icon:Contact,fields:['Name','Phone','Email','Company'],build:v=>`BEGIN:VCARD\nVERSION:3.0\nFN:${v.Name||''}\nORG:${v.Company||''}\nTEL:${v.Phone||''}\nEMAIL:${v.Email||''}\nEND:VCARD`},{id:'event',name:'Event',icon:CalendarDays,fields:['Title','Start','End','Location'],build:v=>`BEGIN:VEVENT\nSUMMARY:${v.Title||''}\nDTSTART:${(v.Start||'').replace(/[-:]/g,'')}\nDTEND:${(v.End||'').replace(/[-:]/g,'')}\nLOCATION:${v.Location||''}\nEND:VEVENT`},{id:'email',name:'Email',icon:Mail,fields:['Email','Subject','Message'],build:v=>`mailto:${v.Email||''}?subject=${encodeURIComponent(v.Subject||'')}&body=${encodeURIComponent(v.Message||'')}`},{id:'sms',name:'SMS',icon:MessageSquare,fields:['Phone','Message'],build:v=>`sms:${v.Phone||''}?body=${encodeURIComponent(v.Message||'')}`},{id:'geo',name:'Location',icon:MapPin,fields:['Latitude','Longitude'],build:v=>`geo:${v.Latitude||''},${v.Longitude||''}`}];
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());const download=(url,name)=>{const a=document.createElement('a');a.href=url;a.download=name;a.click()};
function App(){const[theme,setTheme]=useState(localStorage.qrixTheme||'dark'),[page,setPage]=useState(location.hash==='#studio'?'studio':'home'),[installPrompt,setInstallPrompt]=useState(null),[mode,setMode]=useState('single'),[type,setType]=useState('qr'),[text,setText]=useState('https://qrix.studio/hello'),[fg,setFg]=useState('#111318'),[bg,setBg]=useState('#ffffff'),[size,setSize]=useState(420),[ec,setEc]=useState('H'),[logo,setLogo]=useState(null),[logoSize,setLogoSize]=useState(18),[template,setTemplate]=useState(null),[fields,setFields]=useState({}),[history,setHistory]=useState(()=>JSON.parse(localStorage.qrixHistory||'[]')),[favorite,setFavorite]=useState(()=>JSON.parse(localStorage.qrixFavorites||'[]')),[batch,setBatch]=useState('https://qrix.studio\nSKU-001\nSKU-002'),[batchResults,setBatchResults]=useState([]),[toast,setToast]=useState(''),[scanner,setScanner]=useState(false),[customize,setCustomize]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[compare,setCompare]=useState(false),[stack,setStack]=useState([]),[redo,setRedo]=useState([]);const canvas=useRef(),svgRef=useRef('');
useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.qrixTheme=theme},[theme]);useEffect(()=>localStorage.qrixHistory=JSON.stringify(history),[history]);useEffect(()=>localStorage.qrixFavorites=JSON.stringify(favorite),[favorite]);
useEffect(()=>{const hash=()=>setPage(location.hash==='#studio'?'studio':'home');addEventListener('hashchange',hash);const prompt=e=>{e.preventDefault();setInstallPrompt(e)};addEventListener('beforeinstallprompt',prompt);if('serviceWorker'in navigator)navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`);return()=>{removeEventListener('hashchange',hash);removeEventListener('beforeinstallprompt',prompt)}},[]);
const goStudio=()=>{location.hash='studio';setPage('studio');scrollTo({top:0,behavior:'smooth'})};const goHome=()=>{window.history.replaceState(null,'',location.pathname);setPage('home');scrollTo({top:0,behavior:'smooth'})};const install=async()=>{if(installPrompt){await installPrompt.prompt();setInstallPrompt(null)}else notify('Use your browser menu and choose “Install app”')};
const valid=useMemo(()=>type==='upc'?/^\d{11,12}$/.test(text):type==='ean13'?/^\d{12,13}$/.test(text):!!text,[text,type]);
const render=async(target=canvas.current,t=text,ty=type)=>{if(!target||!t)return;try{if(ty==='qr'){await QRCode.toCanvas(target,t,{width:size,margin:4,errorCorrectionLevel:ec,color:{dark:fg,light:bg}});svgRef.current=await QRCode.toString(t,{type:'svg',margin:4,errorCorrectionLevel:ec,color:{dark:fg,light:bg}});if(logo){const ctx=target.getContext('2d'),img=new Image();img.onload=()=>{const w=target.width*logoSize/100,x=(target.width-w)/2;ctx.fillStyle=bg;ctx.beginPath();ctx.roundRect(x-8,x-8,w+16,w+16,14);ctx.fill();ctx.drawImage(img,x,x,w,w)};img.src=logo}}else{JsBarcode(target,t,{format:ty==='upc'?'UPC':ty==='ean13'?'EAN13':'CODE128',lineColor:fg,background:bg,width:2,height:130,displayValue:true,font:'Inter'})}}catch{}}
useEffect(()=>{if(valid)render()},[text,type,fg,bg,size,ec,logo,logoSize,valid]);
const mutate=(next)=>{setStack(s=>[...s.slice(-19),{text,type,fg,bg,size,ec}]);setRedo([]);next()};const undo=()=>{if(!stack.length)return;const prev=stack.at(-1);setRedo(r=>[{text,type,fg,bg,size,ec},...r]);setStack(s=>s.slice(0,-1));Object.entries(prev).forEach(([k,v])=>({text:setText,type:setType,fg:setFg,bg:setBg,size:setSize,ec:setEc}[k](v)))};const redoIt=()=>{if(!redo.length)return;setStack(s=>[...s,{text,type,fg,bg,size,ec}]);const n=redo[0];setRedo(r=>r.slice(1));Object.entries(n).forEach(([k,v])=>({text:setText,type:setType,fg:setFg,bg:setBg,size:setSize,ec:setEc}[k](v)))};
const notify=m=>{setToast(m);setTimeout(()=>setToast(''),1800)};const record=()=>{if(!valid)return;setHistory(h=>[{id:uid(),text,type,at:Date.now()},...h.filter(x=>!(x.text===text&&x.type===type))].slice(0,50))};
const png=()=>{record();download(canvas.current.toDataURL('image/png'),`qrix-${type}-${Date.now()}.png`);notify('PNG downloaded')};const svg=()=>{record();download(URL.createObjectURL(new Blob([svgRef.current],{type:'image/svg+xml'})),`qrix-${Date.now()}.svg`);notify('SVG downloaded')};const copy=async()=>{try{const b=await(await fetch(canvas.current.toDataURL())).blob();await navigator.clipboard.write([new ClipboardItem({'image/png':b})]);notify('Image copied')}catch{await navigator.clipboard.writeText(text);notify('Payload copied')}};
useEffect(()=>{const key=e=>{if(!(e.ctrlKey||e.metaKey))return;if(e.key==='d'){e.preventDefault();png()}if(e.key==='Enter'&&mode==='batch'){e.preventDefault();generateBatch()}if(['1','2','3','4'].includes(e.key)){e.preventDefault();setType(TYPES[+e.key-1][0])}if(e.key==='z'){e.preventDefault();e.shiftKey?redoIt():undo()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)});
const applyTemplate=t=>{setTemplate(t);setFields({});setType('qr')};useEffect(()=>{if(template)setText(template.build(fields))},[fields,template]);
const generateBatch=async()=>{const lines=batch.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,200),res=[];for(const item of lines){const c=document.createElement('canvas');try{if(type==='qr')await QRCode.toCanvas(c,item,{width:320,margin:4,errorCorrectionLevel:ec,color:{dark:fg,light:bg}});else JsBarcode(c,item,{format:type==='upc'?'UPC':type==='ean13'?'EAN13':'CODE128',lineColor:fg,background:bg,height:100});res.push({item,url:c.toDataURL()})}catch{res.push({item,error:true})}}setBatchResults(res);notify(`${res.filter(x=>!x.error).length} codes minted`)};
const zipAll=async()=>{const z=new JSZip();batchResults.filter(x=>x.url).forEach((r,i)=>z.file(`${String(i+1).padStart(3,'0')}-${r.item.replace(/\W+/g,'-').slice(0,30)}.png`,r.url.split(',')[1],{base64:true}));download(URL.createObjectURL(await z.generateAsync({type:'blob'})),'qrix-batch.zip')};
const scanFile=async e=>{const file=e.target.files[0];if(!file)return;if(!('BarcodeDetector'in window)){notify('Scanner not supported in this browser');return}try{const b=await createImageBitmap(file),d=new BarcodeDetector({formats:['qr_code','code_128','ean_13','upc_a']}),r=await d.detect(b);if(r[0]){setText(r[0].rawValue);setMode('single');setScanner(false);notify('Code scanned')}}catch{notify('Could not read that image')}};
const stats=useMemo(()=>{const counts=history.reduce((a,x)=>(a[x.type]=(a[x.type]||0)+1,a),{});return{total:history.length,top:Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—',unique:new Set(history.map(x=>x.text)).size}},[history]);
return <main className={page==='studio'?'app-page':'landing-page'}><div className="noise"/><header><button className="brand" onClick={goHome}><span className="mark"><QrCode/></span><span>QRix <b>Minter</b></span></button><div className="header-actions"><span className="privacy"><ShieldCheck/> On-device & private</span>{page==='studio'&&<><button className="icon" onClick={undo} disabled={!stack.length} aria-label="Undo"><Undo2/></button><button className="icon" onClick={redoIt} disabled={!redo.length} aria-label="Redo"><Redo2/></button></>}<button className="install-head" onClick={install}><Download/> Install</button><button className="icon" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Theme">{theme==='dark'?<Sun/>:<Moon/>}</button></div></header>
{page==='home'?<Landing goStudio={goStudio} install={install}/>:<><section className="app-intro"><div><span className="eyebrow"><Sparkles/> CODE STUDIO</span><h1>What will you mint?</h1></div><div className="metrics"><div><strong>{stats.total}</strong><span>codes minted</span></div><div><strong>{stats.unique}</strong><span>unique payloads</span></div><div><strong>{stats.top.toUpperCase()}</strong><span>most used</span></div></div></section>
<nav className="modebar">{[['single',QrCode,'Create'],['templates',Layers3,'Templates'],['batch',FileArchive,'Batch'],['scan',ScanLine,'Scan']].map(([m,I,l])=><button className={mode===m?'active':''} onClick={()=>{setMode(m);if(m==='scan')setScanner(true)}}><I/>{l}</button>)}</nav>
{mode==='templates'&&<section className="template-page"><div className="section-head"><div><span className="kicker">SMART PAYLOADS</span><h2>Start with intent, not syntax.</h2><p>Choose a format and QRix assembles the standards-friendly payload for you.</p></div></div><div className="template-grid">{TEMPLATES.map(t=><button className="template-card" onClick={()=>{applyTemplate(t);setMode('single')}}><span><t.icon/></span><b>{t.name}</b><small>{t.fields.join(' · ')}</small><Plus/></button>)}</div></section>}
{mode==='scan'&&<section className="scan-page"><div className="scan-visual"><ScanLine/><div className="scan-corners"/></div><h2>Read a code</h2><p>Upload a QR or barcode image. Detection happens locally when your browser supports it.</p><label className="primary"><Upload/> Choose image<input type="file" accept="image/*" onChange={scanFile}/></label></section>}
{mode==='single'&&<section className="studio"><aside className="controls"><div className="section-label">FORMAT</div><div className="types">{TYPES.map(([id,label,I],i)=><button onClick={()=>mutate(()=>setType(id))} className={type===id?'active':''}><I/><span>{label}</span><kbd>⌘{i+1}</kbd></button>)}</div>
{template&&<div className="template-form"><div className="row"><div className="section-label">{template.name.toUpperCase()} TEMPLATE</div><button className="text-btn" onClick={()=>setTemplate(null)}>Clear</button></div>{template.fields.map(f=><label>{f}<input type={/Start|End/.test(f)?'datetime-local':'text'} value={fields[f]||''} onChange={e=>setFields({...fields,[f]:e.target.value})}/></label>)}</div>}
<label className="payload"><span>CONTENT</span><textarea value={text} onChange={e=>mutate(()=>setText(e.target.value))} placeholder="Paste a URL, text, or identifier…"/><small>{text.length} characters <button onClick={()=>setText('')}>Clear</button></small></label>
<button className="disclosure" onClick={()=>setCustomize(!customize)}><span><Palette/> Appearance</span><ChevronDown className={customize?'flip':''}/></button>{customize&&<div className="custom"><span className="section-label">COLOR PAIRS</span><div className="swatches">{PRESETS.map(([n,a,b])=><button title={n} onClick={()=>mutate(()=>{setFg(a);setBg(b)})} style={{'--a':a,'--b':b}}/>)}</div><div className="color-row"><label>Ink<input type="color" value={fg} onChange={e=>setFg(e.target.value)}/></label><label>Paper<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></div>{type==='qr'&&<><label>Recovery <select value={ec} onChange={e=>setEc(e.target.value)}><option>L</option><option>M</option><option>Q</option><option>H</option></select></label><label>Output size <input type="range" min="240" max="960" step="60" value={size} onChange={e=>setSize(+e.target.value)}/><small>{size}px</small></label><label className="upload"><ImagePlus/> Add center logo<input type="file" accept="image/*" onChange={e=>{const r=new FileReader();r.onload=()=>setLogo(r.result);r.readAsDataURL(e.target.files[0])}}/></label>{logo&&<label>Logo size <input type="range" min="10" max="24" value={logoSize} onChange={e=>setLogoSize(+e.target.value)}/><small>{logoSize}%</small></label>}</>}</div>}
<button className="disclosure" onClick={()=>setHistoryOpen(!historyOpen)}><span><History/> Recent work <i>{history.length}</i></span><ChevronDown className={historyOpen?'flip':''}/></button>{historyOpen&&<div className="history-list">{[...favorite,...history.filter(h=>!favorite.some(f=>f.id===h.id))].slice(0,8).map(h=><div onClick={()=>{setText(h.text);setType(h.type)}}><button onClick={e=>{e.stopPropagation();setFavorite(f=>f.some(x=>x.id===h.id)?f.filter(x=>x.id!==h.id):[h,...f])}}><Star fill={favorite.some(x=>x.id===h.id)?'currentColor':'none'}/></button><span><b>{h.type}</b><small>{h.text}</small></span><button onClick={e=>{e.stopPropagation();setHistory(v=>v.filter(x=>x.id!==h.id))}}><Trash2/></button></div>)}{!history.length&&<p className="empty">Your minted codes will appear here.</p>}</div>}</aside>
<section className="preview"><div className="preview-top"><span>LIVE PROOF</span><div><button onClick={()=>setCompare(!compare)} className={compare?'on':''}><BarChart3/> Compare</button><span className={'status '+(valid?'good':'bad')}>{valid?<><Check/> Ready</>:<>Needs valid input</>}</span></div></div><div className={'canvas-stage '+(compare?'comparing':'')}>{valid?<><div className="code-wrap"><canvas ref={canvas}/><span>QRIX / {type.toUpperCase()}</span></div>{compare&&<Compare text={text} fg={fg} bg={bg}/>}</>:<div className="empty-state"><div><QrCode/></div><h3>Awaiting a valid payload</h3><p>{type==='upc'?'Enter 11 or 12 digits':type==='ean13'?'Enter 12 or 13 digits':'Add content to mint your code'}</p></div>}</div><div className="quality"><ShieldCheck/><div><b>Scan confidence: High</b><span>4-module quiet zone · {ec} recovery · strong contrast</span></div></div><div className="actions"><button className="primary" disabled={!valid} onClick={png}><Download/> Download PNG <kbd>⌘D</kbd></button>{type==='qr'&&<button disabled={!valid} onClick={svg}><Code2/> SVG</button>}<button disabled={!valid} onClick={copy}><Copy/> Copy</button><button disabled={!valid} onClick={()=>window.print()}><Printer/></button></div></section></section>}
{mode==='batch'&&<section className="batch-page"><div className="batch-input"><span className="kicker">BATCH MINT</span><h2>From list to labels<br/>in one clean pass.</h2><p>Paste one value per line, or drop in a .txt/.csv file. Up to 200 codes per batch.</p><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const r=new FileReader();r.onload=()=>setBatch(r.result);r.readAsText(e.dataTransfer.files[0])}}><Upload/><b>Drop a list here</b><span>CSV or TXT</span><label>Browse<input type="file" accept=".txt,.csv" onChange={e=>{const r=new FileReader();r.onload=()=>setBatch(r.result);r.readAsText(e.target.files[0])}}/></label></div><textarea value={batch} onChange={e=>setBatch(e.target.value)}/><div className="batch-foot"><span>{batch.split(/\n/).filter(Boolean).length} items</span><button className="primary" onClick={generateBatch}><Sparkles/> Mint all</button></div></div><div className="batch-output"><div className="row"><h3>Output</h3>{batchResults.length>0&&<div><button onClick={()=>window.print()}><Printer/> Print sheet</button><button onClick={zipAll}><FileArchive/> Download ZIP</button></div>}</div><div className="result-grid">{batchResults.map((r,i)=><article className={r.error?'error':''}>{r.url?<img src={r.url}/>:<X/>}<span>{String(i+1).padStart(2,'0')}</span><b>{r.item}</b>{r.url&&<button onClick={()=>download(r.url,`qrix-${i+1}.png`)}><Download/></button>}</article>)}</div>{!batchResults.length&&<div className="batch-empty"><Layers3/><p>Your minted batch will appear here.</p></div>}</div></section>}</>}
<footer><span>QRix Minter <b>© 2026</b></span><span>Everything stays on your device.</span><button onClick={()=>notify('Shortcuts: ⌘1–4 types · ⌘D download · ⌘↵ batch')}><Command/> Shortcuts</button></footer>{toast&&<div className="toast"><Check/>{toast}</div>}</main>}
function Compare({text,fg,bg}){const ref=useRef();useEffect(()=>{try{JsBarcode(ref.current,text,{format:'CODE128',lineColor:fg,background:bg,height:110,displayValue:false})}catch{}},[text,fg,bg]);return <div className="code-wrap"><canvas ref={ref}/><span>QRIX / CODE128</span></div>}
function Landing({goStudio,install}){return <><section className="landing-hero"><div className="hero-copy"><span className="eyebrow"><Sparkles/> PRIVATE BY DESIGN · READY FOR PRINT</span><h1>One tiny square.<br/><em>Endless connections.</em></h1><p>Design QR codes and barcodes that look sharp, scan reliably, and stay entirely on your device.</p><div className="hero-actions"><button className="primary" onClick={goStudio}>Open the studio <ArrowRight/></button><button onClick={install}><Download/> Install the app</button></div><div className="trust"><span><Check/> No account</span><span><Check/> No uploads</span><span><Check/> Works offline</span></div></div><div className="hero-art" aria-label="Decorative QR code preview"><div className="orbit one">WIFI</div><div className="orbit two">SVG</div><div className="mint-card"><div className="mini-qr">{Array.from({length:81},(_,i)=><i className={(i%9<3&&Math.floor(i/9)<3)||(i%9>5&&Math.floor(i/9)<3)||(i%9<3&&Math.floor(i/9)>5)||[13,22,31,39,41,48,50,58,60,67,69,70,71,75,77,79].includes(i)?'on':''}/>)}</div><span>QRIX / READY</span></div></div></section><section className="landing-features"><div className="feature-lead"><span className="kicker">BUILT DIFFERENT</span><h2>A complete code studio,<br/>without the complexity.</h2></div><div className="feature-grid"><article><Layers3/><b>Smart templates</b><p>Wi-Fi, contacts, events, email, SMS, and locations—without memorizing payload syntax.</p></article><article><Palette/><b>Brand-ready output</b><p>Fine-tune colors, add a center logo, and export crisp PNG or infinitely scalable SVG.</p></article><article><FileArchive/><b>Batch at speed</b><p>Drop a CSV, mint up to 200 codes, then export a ZIP or a print-ready label sheet.</p></article><article><WifiOff/><b>Offline and private</b><p>Install QRix and keep working. Your payloads and designs never leave the device.</p></article></div></section><section className="landing-cta"><div><span className="eyebrow"><Zap/> ZERO SETUP</span><h2>Ready when you are.</h2><p>Open the studio and mint your first production-ready code in seconds.</p></div><button className="primary" onClick={goStudio}>Start minting <ArrowRight/></button></section></>}
createRoot(document.getElementById('root')).render(<App/>);
